# Generated by Django 5.2.7 on 2025-12-06 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('EN_EDITION', 'En Édition'), ('QUESTIONNAIRE_SOUMIS', 'Questionnaire Soumis'), ('IA1_INCOHERENT', 'IA1 Incohérent'), ('IA1_COHERENT', 'IA1 Cohérent'), ('ARCHI_UPLOAD_EN_COURS', 'Architecture Upload En Cours'), ('IA2_INCOHERENT', 'IA2 Incohérent'), ('IA2_COHERENT', 'IA2 Cohérent'), ('RISQUES_EN_COURS', 'Risques En Cours'), ('PRET_VALIDATION', 'Prêt pour Validation Finale'), ('VALIDE', 'Validé')], default='EN_EDITION', max_length=30, verbose_name='Statut du Dossier')),
                ('questionnaire_json', models.JSONField(blank=True, default=dict, null=True)),
                ('questionnaire_model', models.JSONField(blank=True, default=dict, null=True)),
                ('autosave_version', models.IntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('AM', 'Application Manager'), ('SO', 'Security Officer'), ('ADMIN', 'Administrator')], default='AM', max_length=5, verbose_name="Rôle de l'utilisateur")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='audit_log', serialize=False, to='core.dossier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IaCheck',
            fields=[
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ia1_result', serialize=False, to='core.dossier')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], default='PENDING', max_length=10)),
                ('findings', models.JSONField(default=dict)),
                ('secure_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Score de sécurité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IaCrossCheck',
            fields=[
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ia2_result', serialize=False, to='core.dossier')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], default='PENDING', max_length=10)),
                ('findings', models.JSONField(default=dict)),
                ('secure_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Score de sécurité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='am',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Application Manager'),
        ),
        migrations.CreateModel(
            name='ArchitectureDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=255)),
                ('rssi_confirmed', models.BooleanField(default=False)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_docs', to='core.dossier')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis à acceptation'), ('PARTIALLY_ACCEPTED', 'Partiellement accepté'), ('ACCEPTED', 'Accepté')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_created', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_register', to='core.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='RiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du risque')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('likelihood', models.CharField(choices=[('RARE', 'Rare'), ('UNLIKELY', 'Peu probable'), ('POSSIBLE', 'Possible'), ('LIKELY', 'Probable'), ('ALMOST_CERTAIN', 'Quasi-certain')], default='POSSIBLE', max_length=20, verbose_name='Probabilité')),
                ('impact', models.CharField(choices=[('MINOR', 'Mineur'), ('MODERATE', 'Modéré'), ('MAJOR', 'Majeur'), ('SEVERE', 'Sévère'), ('CATASTROPHIC', 'Catastrophique')], default='MODERATE', max_length=20, verbose_name='Impact')),
                ('level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=10, verbose_name='Niveau de risque')),
                ('mitigation', models.TextField(blank=True, verbose_name='Mesures de mitigation')),
                ('status', models.CharField(choices=[('PENDING', "En attente d'acceptation"), ('DELEGATED', 'Délégué'), ('ACCEPTED', 'Accepté')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_items_delegated', to=settings.AUTH_USER_MODEL, verbose_name='Délégué à')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_items_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire du risque')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.riskregister')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DOSSIER_CREATED', 'Dossier créé'), ('DOSSIER_UPDATED', 'Dossier modifié'), ('STATUS_CHANGED', 'Statut modifié'), ('QUESTIONNAIRE_SAVED', 'Questionnaire sauvegardé'), ('QUESTIONNAIRE_SUBMITTED', 'Questionnaire soumis'), ('DOCUMENT_UPLOADED', 'Document uploadé'), ('DOCUMENT_DELETED', 'Document supprimé'), ('DOCUMENT_CONFIRMED', 'Document confirmé par RSSI'), ('IA1_STARTED', 'Analyse IA1 lancée'), ('IA1_COMPLETED', 'Analyse IA1 terminée'), ('IA2_STARTED', 'Analyse IA2 lancée'), ('IA2_COMPLETED', 'Analyse IA2 terminée'), ('RISK_REGISTER_CREATED', 'Registre de risques créé'), ('RISK_ITEM_ADDED', 'Risque ajouté'), ('RISK_ITEM_UPDATED', 'Risque modifié'), ('RISK_ITEM_DELETED', 'Risque supprimé'), ('RISK_ITEM_DELEGATED', 'Risque délégué'), ('RISK_ITEM_ACCEPTED', 'Risque accepté'), ('RISK_REGISTER_SUBMITTED', 'Registre soumis'), ('RISK_REGISTER_ACCEPTED', 'Registre accepté'), ('DOSSIER_VALIDATED', 'Dossier validé')], max_length=30, verbose_name="Type d'action")),
                ('field_modified', models.CharField(blank=True, max_length=100, verbose_name='Champ modifié')),
                ('old_value', models.TextField(blank=True, verbose_name='Ancienne valeur')),
                ('new_value', models.TextField(blank=True, verbose_name='Nouvelle valeur')),
                ('detail', models.JSONField(default=dict, verbose_name='Détails supplémentaires')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.auditlog')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Entrées d'audit",
                'ordering': ['-timestamp'],
            },
        ),
    ]
