# Generated by Django 5.2.7 on 2025-10-22 12:29

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('AM', 'Application Manager'), ('SO', 'Security Officer'), ('ADMIN', 'Administrator')], default='AM', max_length=5, verbose_name="Rôle de l'utilisateur")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('EN_EDITION', 'En Édition'), ('QUESTIONNAIRE_SOUMIS', 'Questionnaire Soumis'), ('IA1_INCOHERENT', 'IA1 Incohérent'), ('IA1_COHERENT', 'IA1 Cohérent'), ('ARCHI_UPLOAD_EN_COURS', 'Architecture Upload En Cours'), ('IA2_INCOHERENT', 'IA2 Incohérent'), ('IA2_COHERENT', 'IA2 Cohérent'), ('RISQUES_EN_COURS', 'Risques En Cours'), ('PRET_VALIDATION', 'Prêt pour Validation Finale'), ('VALIDE', 'Validé')], default='EN_EDITION', max_length=30, verbose_name='Statut du Dossier')),
                ('questionnaire_json', models.JSONField(default=dict)),
                ('questionnaire_model', models.JSONField(default=dict)),
                ('autosave_version', models.IntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('am', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Application Manager')),
            ],
        ),
    ]
