# Generated by Django 5.2.7 on 2025-12-06 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom du questionnaire')),
                ('description', models.TextField(blank=True, verbose_name='Description du questionnaire')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Modèle de questionnaire',
                'verbose_name_plural': 'Modèles de questionnaire',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('text', models.TextField(verbose_name='Texte de la question')),
                ('question_type', models.CharField(choices=[('TRUE_FALSE', 'Vrai/Faux'), ('MULTIPLE_CHOICE', 'Choix multiples'), ('SINGLE_CHOICE', 'Choix unique'), ('TEXT', 'Texte libre')], max_length=20, verbose_name='Type de question')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('choices_json', models.JSONField(blank=True, default=list, help_text="Liste des options pour choix multiples/uniques. Format: ['option1', 'option2', ...]", verbose_name='Options')),
                ('help_text', models.TextField(blank=True, verbose_name="Texte d'aide")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.questionnairetemplate', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['template', 'order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='questionnaire_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='core.questionnairetemplate', verbose_name='Modèle de questionnaire'),
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.TextField(blank=True, null=True, verbose_name='Réponse')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Date de réponse')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to='core.dossier', verbose_name='Dossier')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse au questionnaire',
                'verbose_name_plural': 'Réponses au questionnaire',
                'ordering': ['dossier', 'question__order'],
                'unique_together': {('dossier', 'question')},
            },
        ),
    ]
