# Generated by Django 5.2.7 on 2025-11-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='dossier',
            name='questionnaire_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='questionnaire_model',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
