# Generated by Django 5.2.7 on 2025-12-06 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_questionnairetemplate_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireanswer',
            name='answer_value',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='Réponse'),
            preserve_default=False,
        ),
    ]
