# Generated by Django 5.2.7 on 2025-12-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_questionnaireanswer_answer_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='autosave_version',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='questionnaire_json',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='questionnaire_model',
        ),
    ]
