# Generated by Django 5.2.7 on 2025-12-06 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dossier_autosave_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='responsible_so',
            field=models.ForeignKey(blank=True, help_text='The Security Officer responsible for this dossier', limit_choices_to={'role': 'SO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Responsible Security Officer'),
        ),
    ]
