# Generated by Django 5.2.7 on 2025-12-07 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dossier_responsible_so'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecturedoc',
            name='s3_key',
        ),
        migrations.AddField(
            model_name='architecturedoc',
            name='local_filepath',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Chemin local du fichier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='architecturedoc',
            name='site_filepath',
            field=models.CharField(default=django.utils.timezone.now, help_text='URL relative pour télécharger le fichier, ex: /api/dossiers/1/documents/document.pdf', max_length=255, verbose_name="Chemin d'accès pour téléchargement"),
            preserve_default=False,
        ),
    ]
