# Generated by Django 5.2.7 on 2025-12-07 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_architecturedoc_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskitem',
            name='contestation_reason',
            field=models.TextField(blank=True, verbose_name='Raison de la contestation'),
        ),
        migrations.AddField(
            model_name='riskitem',
            name='contested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskitem',
            name='contested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_items_contested', to=settings.AUTH_USER_MODEL, verbose_name='Contesté par'),
        ),
        migrations.AddField(
            model_name='riskitem',
            name='refused_by',
            field=models.JSONField(blank=True, default=list, help_text='List of user IDs who refused this delegation', verbose_name='Refusé par'),
        ),
        migrations.AlterField(
            model_name='riskitem',
            name='status',
            field=models.CharField(choices=[('PENDING', "En attente d'acceptation"), ('DELEGATED_PENDING', 'Délégué - En attente'), ('ACCEPTED', 'Accepté'), ('CONTESTED', 'Contesté'), ('REFUSED', 'Refusé')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
    ]
