# Generated by Django 5.2.7 on 2025-12-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_riskitem_contestation_reason_riskitem_contested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iacheck',
            name='raw_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
