# Generated by Django 5.2.7 on 2025-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_iacheck_raw_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='architecture_docs_submitted',
            field=models.BooleanField(default=False, help_text='Set to True when AM submits all architecture documents. Prevents further uploads.'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='status',
            field=models.CharField(choices=[('EN_EDITION', 'En Édition'), ('QUESTIONNAIRE_SOUMIS', 'Questionnaire Soumis'), ('IA1_INCOHERENT', 'IA1 Incohérent'), ('IA1_COHERENT', 'IA1 Cohérent'), ('ARCHI_UPLOAD_EN_COURS', 'Architecture Upload En Cours'), ('IA2_INCOHERENT', 'IA2 Incohérent'), ('IA2_COHERENT', 'IA2 Cohérent'), ('RISQUES_EN_COURS', 'Risques En Cours'), ('PRET_VALIDATION', 'Prêt pour Validation Finale'), ('VALIDE', 'Validé')], default='EN_EDITION', max_length=50),
        ),
    ]
