# Generated by Django 5.2.7 on 2025-12-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dossier_architecture_docs_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecturedoc',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='architecturedoc',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom affiché'),
        ),
    ]
