# Generated by Django 5.2.7 on 2025-12-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_architecturedoc_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskitem',
            name='contest_refused',
            field=models.BooleanField(default=False, help_text='True if SO refused the contestation. Prevents further contestation.', verbose_name='Contestation refusée'),
        ),
        migrations.AlterField(
            model_name='riskitem',
            name='impact',
            field=models.CharField(choices=[('MINOR', 'Mineur'), ('MODERATE', 'Moyen'), ('MAJOR', 'Élevé'), ('SEVERE', 'Critique'), ('CATASTROPHIC', 'Catastrophique')], default='MODERATE', max_length=20, verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='riskitem',
            name='status',
            field=models.CharField(choices=[('PENDING', "En attente d'acceptation"), ('DELEGATED_PENDING', 'Délégué - En attente'), ('ACCEPTED', 'Accepté'), ('CONTESTED', 'Contesté'), ('REFUSED', 'Refusé'), ('INVALIDATED', 'Invalidé (Contestation acceptée)')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
    ]
